package igrey.dev.nonblockingdemo.const

object Constants {
    val IMDB_TOP_250 = listOf(
        "The Shawshank Redemption",
        "The Godfather",
        "The Godfather: Part II",
        "The Dark Knight",
        "12 Angry Men",
        "Pulp Fiction",
        "Il Maestro: Ennio Morricone and 'The Good, the Bad and the Ugly'",
        "The Lord of the Rings: The Return of the King",
        "Star Wars: Episode V - The Empire Strikes Back",
        "Modern Times",
        "Memento",
        "Apocalypse Now",
        "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
        "Alien",
        "WALL·E",
        "Citizen Kane",
        "Braveheart",
        "The Apartment",
        "All About Eve",
        "Inglourious Basterds",
        "3 Idiots",
        "Mad Max: Fury Road",
        "Ran",
        "Blade Runner",
        "Judgment at Nuremberg",
        "A Beautiful Mind",
        "Fargo",
        "No Country for Old Men",
        "There Will Be Blood",
        "Annie Hall",
        "The Grand Budapest Hotel",
        "Forrest Gump",
        "Schindler's List",
        "The Lord of the Rings: The Two Towers",
        "One Flew Over the Cuckoo's Nest",
        "Fight Club",
        "Star Wars",
        "Inception",
        "Goodfellas",
        "Life Is Beautiful",
        "Once Upon a Time in the West Oakland",
        "The Matrix",
        "The Silence of the Lambs",
        "Se7en",
        "Interstellar",
        "Saving Private Ryan",
        "It's a Wonderful Life",
        "The Usual Suspects",
        "American History X",
        "Spirited Away",
        "Casablanca",
        "City Lights",
        "Whiplash",
        "Terminator 2: Judgment Day",
        "Psycho",
        "Raiders of the Lost Ark",
        "City of God",
        "Diabolique",
        "The Pianist",
        "Stalker",
        "The Departed",
        "Sunset Blvd.",
        "Twelve Monkeys",
        "Rear Window",
        "The Green Mile",
        "Infernal affairs 1: Origines d'une saga",
        "Seven Samurai: Origins and Influences",
        "The Prestige",
        "The Shining",
        "Back to the Future",
        "Gladiator",
        "Django Unchained",
        "The Dark Knight Rises",
        "Harry Potter and the Deathly Hallows: Part 2",
        "The Lion King",
        "The Lives Of Others",
        "Inside Out",
        "Nuovo Cinema Paradiso",
        "The Great Dictator",
        "Oldeuboi",
        "Das Boot",
        "Vertigo",
        "Grave of the Fireflies",
        "Aliens",
        "Who's Afraid of Virginia Woolf?",
        "Amélie",
        "American Beauty",
        "Reservoir Dogs",
        "North by Northwest",
        "Star Wars: Episode VI - Return of the Jedi",
        "Double Indemnity",
        "Toy Story 3",
        "A Clockwork Orange",
        "To Kill a Mockingbird",
        "Witness for the Prosecution",
        "Once Upon a Time in America",
        "Full Metal Jacket",
        "Paris, Texas",
        "Amadeus",
        "Eternal Sunshine of the Spotless Mind",
        "M",
        "Snatch",
        "Bicycle Thieves",
        "Requiem for a Dream",
        "The Kid",
        "L.A. Confidential",
        "2001: A Space Odyssey",
        "The Sting",
        "Restoration Italian Style: For a Few Dollars More",
        "Taxi Driver",
        "Singin' in the Rain",
        "Lawrence of Arabia",
        "Rashômon",
        "Toy Story",
        "Monty Python and the Holy Grail",
        "The Treasure of the Sierra Madre",
        "Jodaeiye Nader az Simin",
        "The Third Man",
        "Batman Begins",
        "Nihiki no yojimbo",
        "Up",
        "Metropolis",
        "Indiana Jones and the Last Crusade",
        "Good Will Hunting",
        "Some Like It Hot",
        "Die Hard",
        "On the Waterfront",
        "The Great Escape",
        "Scarface",
        "Director's Notebook: Pan's Labyrinth",
        "Raging Bull",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Heat",
        "Mr. Smith Goes to Washington",
        "Chinatown",
        "Ikiru",
        "Jagten",
        "Unforgiven",
        "The Gold Rush",
        "The Wild Strawberries Under the Snow",
        "The General",
        "Lock, Stock and Two Smoking Barrels",
        "The Bridge on the River Kwai",
        "My Neighbor Totoro: The Totoro Experience",
        "The Wolf of Wall Street",
        "Paths of Glory",
        "Gran Torino",
        "The Elephant Man",
        "The Big Lebowski",
        "V for Vendetta",
        "Warrior",
        "The Deer Hunter",
        "Gone with the Wind",
        "Rebecca",
        "Into the Wild",
        "Cool Hand Luke",
        "Dial M for Murder",
        "Finding Nemo",
        "Gone Girl",
        "How to Train Your Dragon",
        "Kill Bill: Vol. 1",
        "Hotel Rwanda",
        "The Sixth Sense",
        "Trainspotting",
        "Rush",
        "Platoon",
        "The Maltese Falcon",
        "Incendies",
        "Life of Brian",
        "The Princess Bride",
        "12 Years a Slave",
        "Stand by Me",
        "Touch of Evil",
        "Amores perros",
        "Butch Cassidy and the Sundance Kid",
        "Persona",
        "Gandhi",
        "Network",
        "The Wizard of Oz",
        "Million Dollar Baby",
        "Ben-Hur",
        "The Best Years of Our Lives",
        "Hachi: A Dog's Tale",
        "Relatos salvajes",
        "In the Name of the Father",
        "Shutter Island",
        "Behind the Microphone: Nausicaa of the Valley of the Wind",
        "Donnie Darko",
        "8½",
        "The Thing",
        "Sin City",
        "The Avengers",
        "Jurassic Park",
        "Jaws",
        "Guardians of the Galaxy",
        "Memories of Murder",
        "The Terminator",
        "Before Sunrise",
        "The Truman Show",
        "Marxist Poetry: The Making of 'The Battle of Algiers'",
        "Barry Lyndon",
        "Rocky",
        "The Imitation Game",
        "Strangers on a Train",
        "The Bourne Ultimatum",
        "Monsters, Inc.",
        "Groundhog Day",
        "The King's Speech",
        "Yip Man 2",
        "La haine",
        "High Noon",
        "Castle in the Sky",
        "Prisoners",
        "Anatomy of a Murder",
        "Pirates of the Caribbean: The Curse of the Black Pearl",
        "The Graduate",
        "Roman Holiday",
        "Gangs of Wasseypur",
        "La strada",
        "Papillon",
        "Beauty and the Beast",
        "Before Sunset",
        "The Big Sleep",
        "The Help",
        "The Hustler",
        "Underground",
        "Lagaan: Once Upon a Time in India",
        "Akira",
        "X-Men: Days of Future Past",
        "Mary and Max.",
        "Dog Day Afternoon",
        "Casino",
        "Notorious",
        "The Night of the Hunter",
        "Princess Mononoke: Making of a Masterpiece",
        "Jean Reno on Leon: The Professional",
        "The Grapes of Wrath",
        "It Happened One Night",
        "Downfall"
    )
}